<body>
	<!-- Automatic element centering using js -->
	<div class="center">            
		<div class="headline text-center" id="time">
			<!-- Time auto generated by js -->
		</div><!-- /.headline -->
		
		<!-- User name -->
		<div class="lockscreen-name" style="color:#AAA"><?php echo get_data_user('name'); ?></div>
		
		<!-- START LOCK SCREEN ITEM -->
		<?php echo form_open('lock_screen'); ?>
		<div class="lockscreen-item">
			<!-- lockscreen image -->
			<div class="lockscreen-image">
				<img src="<?php echo base_url().jarvis_call_configuration('pathAvatar').get_data_user('avatar');?>" alt="user image"/>
			</div>
			<!-- /.lockscreen-image -->

			<!-- lockscreen credentials (contains the form) -->
			
			<div class="lockscreen-credentials">   

				<div class="input-group">
					<input type="password" name="password" class="form-control" placeholder="password" />
					<div class="input-group-btn">
						<button type="submit" class="btn btn-flat"><i class="fa fa-arrow-right text-muted"></i></button>
					</div>			
				</div>
			</div><!-- /.lockscreen credentials -->
		</div><!-- /.lockscreen-item -->
		<div class="lockscreen-link error_lock_screen" style="display:none; color:#989898;">
			<?php echo validation_errors(); ?>
		</div> 
		<?php echo form_close();?>
		<div class="lockscreen-link">
			<a href="<?php echo base_url().'logout';?>">Or sign in as a different user</a>
		</div>           
	</div><!-- /.center -->
